# Generated by Django 6.0.4 on 2026-05-04 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
